### ISSUE TITLE
VoodI2C didn't detect during installation

### ISSUE THREAD

**Issue by ameenjuz** [Sniki/Lenovo-V330-15IKB#2]
VoodoI2C.kext is not working during installation but with Opencore work 
VoodooI2C was working fine during installation earlier version of clover
i think that something has been changed in clover bootloader
do you have idea? 
I tested with rehanbman's Clover_v2.4k_r4701.RM-4963.ca6cca7c worked fine during installation and post installation 
I think that clover has changed something related VoodooI2C or bug  ﻿
do you have working voodI2C during installation?

**Comment by Sniki** [comment]
Are you using latest release of VoodooI2C + VooodooI2CELAN ?

**Comment by ameenjuz** [comment]
yes I m using latest v2.3 VoodooI2C + VooodooI2CELAN

**Comment by Sniki** [comment]
> yes I m using latest v2.3 VoodooI2C + VooodooI2CELAN

I don't know to be honest, use the forums and write me on the Lenovo V330-15IKB guide thread on tmx86 with the problem reporting files so i can take a look and find where the problem comes from.

Closing here
