### ISSUE TITLE
Screen flickering issue with QuickTime player

### ISSUE THREAD

**Issue by ameenjuz** [Sniki/Lenovo-V330-15IKB#4]
I posted my issue to your v330 guide but you didn't replied
I have a issue with Quicktime player

When i play video 1920x1080 60fps with quicktime player the screen flickering black
When i play video 1920x1080 30fps or 25fps video worked  fine no flickering
What is this issue 
Sniki can tell me about this issue i think this issue is related shiki or quicktime player

I m running kabylake i5-7200u  IntelHDGraphic 620

**Comment by Sniki** [comment]
> I posted my issue to your v330 guide but you didn't replied
> I have a issue with Quicktime player
> 
> When i play video 1920x1080 60fps with quicktime player the screen flickering black
> When i play video 1920x1080 30fps or 25fps video worked fine no flickering
> What is this issue
> Sniki can tell me about this issue i think this issue is related shiki or quicktime player
> 
> I m running kabylake i5-7200u IntelHDGraphic 620

To be honest my V330-15IKB is 8th gen Kaby Lake-R (1 generation newer) but i never tested that, it may be specific to the WhateverGreen.kext or QuickTime bug itself.

**Comment by ameenjuz** [comment]
Please test your pc i want to fix this issue since sierra  but couldn't fix

**Comment by Sniki** [comment]
> Please test your pc i want to fix this issue since sierra but couldn't fix

i dont have this device anymore, i sold it.
