### ISSUE TITLE
Creating custom SSDT  

### ISSUE THREAD

**Issue by Ab2774** [Sniki/Lenovo-V330-15IKB#5]
Hi Sniki 
I see that you have a similar laptop to mine and you created custom SSDT for your audio, can you tell me how you did it cuz when I use my mic after putting my laptop on sleep the audio disappears completely and it won't come back until I plug a headphone if I switch to another output it will come back but for only 10 seconds and it will disappear again.
Lenovo Ideapad 320 with i5 7200U, ALC230 layout 20
ALCPlugFix installed for headphone noise after sleep
Codec Commander installed in L/E
Heres my CodecDump
[CodecDump.zip](https://github.com/Sniki/Lenovo-V330-15IKB/files/4301482/CodecDump.zip)
Thanks in advance

**Comment by Sniki** [comment]
Off-topic, use forums please.
Only issues with this hardware and problems on my side.
