### ISSUE TITLE
330s-15IKB

### ISSUE THREAD

**Issue by Leconvic** [Sniki/Lenovo-V330-15IKB#6]
Good day! Will this work on 330s-15IKB (Slim and newer version) with almost the same specs:

i7-8550U(Kaby Lake R)

UHD 620/Radeon 540

Wondering if there will be any SMBIOS changes for my config too!

Thanks!

**Comment by Sniki** [comment]
> Good day! Will this work on 330s-15IKB (Slim and newer version) with almost the same specs:
> 
> i7-8550U(Kaby Lake R)
> 
> UHD 620/Radeon 540
> 
> Wondering if there will be any SMBIOS changes for my config too!
> 
> Thanks!

There shouldn't be any SMBIOS changes but the main change should the ACPI i believe.
You can try.

Note: please use the forums for troubleshooting.
